In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
df_features = pd.read_parquet("/content/drive/MyDrive/data/archive/tts_features.parquet")
df_features.head()

   mfcc_1_mean  mfcc_2_mean  mfcc_3_mean  ...  rms_mean   rms_std            label
0  -231.092453   114.497093     7.188296  ...  0.098040  0.065750  cv4_fastspeech2
1  -378.915619   179.476929     7.342104  ...  0.038649  0.017452  cv4_fastspeech2
2  -398.897552   123.861023    24.483349  ...  0.017969  0.007009  cv4_fastspeech2
3  -389.487488   112.788864     9.360864  ...  0.011842  0.004678  cv4_fastspeech2
4  -270.491730   125.467178    -7.004885  ...  0.072086  0.036683  cv4_fastspeech2

[5 rows x 89 columns]

In [5]:
X = df_features.drop(columns=["label"])
y = df_features["label"]

print(type(X))
print(type(y))
print(X.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(34850, 88)
(34850,)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state= 42, stratify =y)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(27880, 88)
(6970, 88)
(27880,)
(6970,)

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

rf = RandomForestClassifier(n_estimators=200,random_state=42,n_jobs=-1)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
acc = accuracy_score(y_test,y_pred)
print(f"Accuracy: {acc:4f}")
print(classification_report(y_test,y_pred))
cm = confusion_matrix(y_test,y_pred)
print(cm.shape)
print(cm)

importance = rf.feature_importances_
importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": importance
})
importance_df.sort_values(by="Importance",ascending=False,inplace=True)
importance_df.head(10)

Accuracy: 0.870732
                                     precision    recall  f1-score   support

                    cv4_fastspeech2       0.98      0.99      0.99       278
                      ek1_tacotron2       1.00      1.00      1.00       279
                ljspeech_deepvoice3       1.00      1.00      1.00       279
                ljspeech_fast_pitch       0.77      0.73      0.75       279
               ljspeech_fastspeech2       0.96      0.95      0.96       279
                  ljspeech_glow-tts       0.82      0.87      0.85       279
             ljspeech_tacotron2-DCA       0.85      0.84      0.84       279
             ljspeech_tacotron2-DDC       0.80      0.76      0.78       279
          ljspeech_tacotron2-DDC_ph       0.88      0.88      0.88       278
                      ljspeech_vits       0.84      0.86      0.85       279
                   sam_tacotron-DDC       1.00      1.00      1.00       279
                    silero_lj_16khz       0.91      0.96      0.93       278
           silero_lj_16khz_enhanced       0.99      0.97      0.98       279
  tf_ljspeech_FASTSPEECH2_MB-MELGAN       0.81      0.83      0.82       279
     tf_ljspeech_FASTSPEECH2_MELGAN       0.70      0.69      0.70       279
tf_ljspeech_FASTSPEECH2_MELGAN-STFT       0.73      0.68      0.71       279
   tf_ljspeech_FASTSPEECH_MB-MELGAN       0.78      0.85      0.81       278
      tf_ljspeech_FASTSPEECH_MELGAN       0.75      0.68      0.72       279
 tf_ljspeech_FASTSPEECH_MELGAN-STFT       0.73      0.72      0.73       279
        tf_ljspeech_TACOTRON_MELGAN       0.74      0.77      0.76       279
   tf_ljspeech_TACOTRON_MELGAN-STFT       0.81      0.77      0.79       279
      vctk_deepvoice3_speakerrandom       0.99      0.99      0.99       279
      vctk_fast_pitch_speakerrandom       1.00      0.99      0.99       279
     vctk_sc-glow-tts_speakerrandom       0.98      0.96      0.97       278
            vctk_vits_speakerrandom       0.96      0.98      0.97       279

                           accuracy                           0.87      6970
                          macro avg       0.87      0.87      0.87      6970
                       weighted avg       0.87      0.87      0.87      6970

(25, 25)
[[276   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0
    0   0   0   1   0   0   0]
 [  0 278   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   1]
 [  0   0 279   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   1   0 205   0  18  16  21   5  13   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0 266   0   0   0   0   0   0   9   0   1   0   1   0   2
    0   0   0   0   0   0   0]
 [  0   0   0  12   0 243   5   3   6   7   0   0   0   0   0   2   0   0
    0   0   1   0   0   0   0]
 [  0   0   0   8   0  18 235   4   4   4   0   0   0   1   1   0   2   0
    0   1   1   0   0   0   0]
 [  0   0   0  27   0   4  10 212  10  14   0   0   0   0   0   1   0   0
    0   0   0   0   1   0   0]
 [  1   0   0   4   0   1   3  12 246   9   0   0   0   0   0   0   0   0
    0   1   1   0   0   0   0]
 [  0   0   0   8   0   7   5  11   8 240   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 279   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0 267   2   2   1   3   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   8 271   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   2   0 231   0   0  44   0
    0   0   2   0   0   0   0]
 [  0   0   0   0   2   0   1   0   0   0   0   1   0   5 193  13   2  33
    1  26   2   0   0   0   0]
 [  0   0   0   0   1   2   0   0   0   0   0   2   0   9  24 191   3   1
   32   3  11   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   2   0  29   1   2 237   1
    2   1   2   0   0   0   0]
 [  1   0   0   0   2   0   0   0   0   0   0   1   0   1  37   0   1 191
   12  33   0   0   0   0   0]
 [  0   0   0   0   3   1   0   1   0   0   0   0   0   0   1  33   6   7
  202   3  22   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0   0   1   0   6  16   3   4  19
    4 216   9   0   0   0   0]
 [  1   0   0   1   1   1   2   0   1   0   0   2   0   1   2  13   5   0
   25   9 215   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0 277   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   2 277   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0 268  10]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   5 274]]

          Feature  Importance
86       rms_mean    0.048505
0     mfcc_1_mean    0.045597
12   mfcc_13_mean    0.035295
87        rms_std    0.034898
13     mfcc_1_std    0.034353
11   mfcc_12_mean    0.030180
4     mfcc_5_mean    0.028553
8     mfcc_9_mean    0.027525
10   mfcc_11_mean    0.023918
83  bandwidth_std    0.022876

In [ ]:
!pip install xgboost

In [14]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

xgb = XGBClassifier(objective = "multi:softmax",num_class = 25,n_estimators =200,max_depth = 8,learning_rate=0.1,random_state = 42,tree_method = "hist",eval_metric ="mlogloss")
xgb.fit(X_train,y_train_enc)
y_pred = xgb.predict(X_test)
acc = accuracy_score(y_test_enc,y_pred)
print(f"Accuracy: {acc:4f}")

y_pred_labels = le.inverse_transform(y_pred)
print(classification_report(y_test,y_pred_labels))
cm = confusion_matrix(y_test,y_pred_labels)
print(cm.shape)
print(cm)

Accuracy: 0.909326
                                     precision    recall  f1-score   support

                    cv4_fastspeech2       0.99      0.99      0.99       278
                      ek1_tacotron2       1.00      1.00      1.00       279
                ljspeech_deepvoice3       1.00      1.00      1.00       279
                ljspeech_fast_pitch       0.88      0.85      0.86       279
               ljspeech_fastspeech2       0.97      0.96      0.97       279
                  ljspeech_glow-tts       0.88      0.91      0.89       279
             ljspeech_tacotron2-DCA       0.91      0.90      0.90       279
             ljspeech_tacotron2-DDC       0.89      0.90      0.90       279
          ljspeech_tacotron2-DDC_ph       0.93      0.92      0.92       278
                      ljspeech_vits       0.90      0.90      0.90       279
                   sam_tacotron-DDC       1.00      1.00      1.00       279
                    silero_lj_16khz       0.96      0.96      0.96       278
           silero_lj_16khz_enhanced       0.99      0.97      0.98       279
  tf_ljspeech_FASTSPEECH2_MB-MELGAN       0.86      0.89      0.87       279
     tf_ljspeech_FASTSPEECH2_MELGAN       0.80      0.77      0.78       279
tf_ljspeech_FASTSPEECH2_MELGAN-STFT       0.80      0.78      0.79       279
   tf_ljspeech_FASTSPEECH_MB-MELGAN       0.87      0.88      0.88       278
      tf_ljspeech_FASTSPEECH_MELGAN       0.77      0.80      0.78       279
 tf_ljspeech_FASTSPEECH_MELGAN-STFT       0.78      0.80      0.79       279
        tf_ljspeech_TACOTRON_MELGAN       0.77      0.76      0.77       279
   tf_ljspeech_TACOTRON_MELGAN-STFT       0.86      0.85      0.85       279
      vctk_deepvoice3_speakerrandom       0.99      0.99      0.99       279
      vctk_fast_pitch_speakerrandom       1.00      1.00      1.00       279
     vctk_sc-glow-tts_speakerrandom       0.99      0.97      0.98       278
            vctk_vits_speakerrandom       0.97      0.99      0.98       279

                           accuracy                           0.91      6970
                          macro avg       0.91      0.91      0.91      6970
                       weighted avg       0.91      0.91      0.91      6970

(25, 25)
[[276   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0
    0   1   0   0   0   0   0]
 [  0 278   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0 278   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   1   0   0   0]
 [  0   1   0 236   0  11  10  12   0   8   0   0   0   0   0   0   0   0
    0   0   1   0   0   0   0]
 [  0   0   0   0 268   0   0   0   0   0   0   4   0   1   1   1   0   1
    0   0   3   0   0   0   0]
 [  0   0   0   8   0 253   7   1   1   5   0   0   0   0   0   3   0   0
    0   0   1   0   0   0   0]
 [  0   0   0   4   0  13 250   2   4   3   0   0   0   1   0   0   0   0
    1   1   0   0   0   0   0]
 [  0   0   0   7   0   1   5 252   7   6   0   0   0   0   0   0   0   0
    1   0   0   0   0   0   0]
 [  0   0   0   5   0   1   0   8 256   7   0   0   0   0   0   0   0   0
    0   0   0   1   0   0   0]
 [  0   0   0   8   0   5   1   6   8 251   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 279   0   0   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0 266   1   1   0   1   2   0
    1   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   8 271   0   0   0   0   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 249   2   0  28   0
    0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   4 215  12   0  29
    0  17   2   0   0   0   0]
 [  0   0   0   0   1   1   0   0   0   0   0   0   1  11  15 219   1   0
   25   1   4   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0  18   0   0 246   3
    7   1   2   0   0   0   0]
 [  0   0   0   0   2   0   0   0   0   0   0   0   0   0  19   0   0 223
   10  24   1   0   0   0   0]
 [  0   0   0   0   1   2   0   1   0   0   0   0   0   0   1  29   2   7
  223   3  10   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0   0   0   0   5  15   1   2  27
    3 212  13   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0   0   0   0   0   1   1   7   1   0
   14  15 238   0   0   0   0]
 [  3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0 275   0   0   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   1 278   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0 271   7]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   4 275]]